---
name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  python-lint-and-scan:
    if: >
      github.event_name == 'push'
      || github.event_name == 'pull_request'
      || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
    uses: dceoy/gha-for-devops/.github/workflows/python-package-lint-and-scan.yml@main  # zizmor: ignore[unpinned-uses]
    with:
      package-path: .
  python-test:
    if: >
      github.event_name == 'push'
      || github.event_name == 'pull_request'
      || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
    uses: dceoy/gha-for-devops/.github/workflows/python-package-test.yml@main   # zizmor: ignore[unpinned-uses]
    with:
      package-path: .
  dependabot-auto-merge:
    if: >
      github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
    needs:
      - python-lint-and-scan
      - python-test
    uses: dceoy/gha-for-devops/.github/workflows/dependabot-auto-merge.yml@main   # zizmor: ignore[unpinned-uses]
    permissions:
      contents: write
      pull-requests: write
      actions: read
      checks: read
      statuses: read
    with:
      unconditional: true
