---
name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        description: Python version to use
        default: 3.x
  workflow_dispatch:
    inputs:
      python-version:
        required: false
        type: string
        description: Python version to use
        default: 3.x
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  lint-and-scan:
    uses: dceoy/gh-actions-for-devops/.github/workflows/python-package-lint-and-scan.yml@main
    with:
      package-path: .
      python-version: ${{ inputs.python-version || '3.x' }}
      mypy-options: --exclude=build --install-types --non-interactive --ignore-missing-imports
  test-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version || '3.x' }}
      - name: Install packages
        run: |
          pip install -U --no-cache-dir .
      - name: Test the class
        shell: python {0}
        run: |
          from shoper.shelloperator import ShellOperator
          sh = ShellOperator()
          sh.run('ls -l')
          sh.run(
              args=[
                  'echo ${RANDOM} | tee random0.txt',
                  'echo ${RANDOM} | tee random1.txt',
                  'echo ${RANDOM} | tee random2.txt'
              ],
              output_files_or_dirs=['random0.txt', 'random1.txt', 'random2.txt']
          )
          sh.run(
              args='sort random[012].txt | tee sorted.txt',
              input_files_or_dirs=['random0.txt', 'random1.txt', 'random2.txt'],
              output_files_or_dirs='sorted.txt'
          )
