---
name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test_installation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install shoper
        run: |
          python3 -m pip install -U \
            autopep8 flake8 flake8-bugbear flake8-isort pep8-naming .
      - name: Validate the codes using flake8
        run: |
          find . -name '*.py' | xargs flake8
      - name: Test the class
        run: |
          cat << EOF | python3
          from shoper.shelloperator import ShellOperator
          sh = ShellOperator()
          sh.run('ls -l')
          sh.run(
              args=[
                  'echo ${RANDOM} | tee random0.txt',
                  'echo ${RANDOM} | tee random1.txt',
                  'echo ${RANDOM} | tee random2.txt'
              ],
              output_files_or_dirs=['random0.txt', 'random1.txt', 'random2.txt']
          )
          sh.run(
              args='sort random[012].txt | tee sorted.txt',
              input_files_or_dirs=['random0.txt', 'random1.txt', 'random2.txt'],
              output_files_or_dirs='sorted.txt'
          )
          EOF
