---
name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        description: Python version to use
        default: 3.x
  workflow_dispatch:
    inputs:
      python-version:
        required: false
        type: string
        description: Python version to use
        default: 3.x
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  lint-and-scan:
    uses: dceoy/gh-actions-for-devops/.github/workflows/python-package-lint-and-scan.yml@main
    with:
      package-path: .
      python-version: ${{ inputs.python-version || '3.x' }}
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: ${{ inputs.python-version || '3.x' }}
      - name: Install dependencies
        run: |
          pip install -U --no-cache-dir pip uv
          uv sync
      - name: Run unit tests
        run: |
          uv run pytest
